/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-09-20 04:56:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class agreement_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/member/../include/header.jsp", Long.valueOf(1663063688388L));
    _jspx_dependants.put("jar:file:/D:/gyujin/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/gmovie/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/member/../include/footer.jsp", Long.valueOf(1663647295402L));
    _jspx_dependants.put("jar:file:/D:/gyujin/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/gmovie/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1659671595531L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>회원약관동의</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/normalize.css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("        .agreement {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            clear: both;\r\n");
      out.write("        }\r\n");
      out.write("        .agreement h2, p {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("        .agreement h2 {\r\n");
      out.write("            padding-top: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .agreement p {\r\n");
      out.write("            margin-top: 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .agreement .mt20 {\r\n");
      out.write("            padding-left: 160px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            line-height: 24px;\r\n");
      out.write("            color: #333333;\r\n");
      out.write("            margin-top: 100px;       \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .agreement .mt20::after {\r\n");
      out.write("            content: \"(필수)\";\r\n");
      out.write("            color: #bb4f1a;\r\n");
      out.write("            margin-left: 7px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .agreeBox {\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            border: 1px solid #e6e6e6;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .agreeBox p {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .agreeBox > div {\r\n");
      out.write("            overflow: auto;\r\n");
      out.write("            height: 200px;\r\n");
      out.write("            padding: 20px 20px;\r\n");
      out.write("            color: #505360;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .blueText {\r\n");
      out.write("            color: #326EB4;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .all_agreement {\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            margin: auto;\r\n");
      out.write("            margin-top: 50px;\r\n");
      out.write("            background-color: #fbfbfb;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .join_agreement {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            padding-top: 15px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn_group {\r\n");
      out.write("            width: 1200px;\r\n");
      out.write("            margin: auto ;\r\n");
      out.write("            margin-top: 25px;\r\n");
      out.write("            height: 100px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn_group .subbtn {\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            background-color: #007dcd;\r\n");
      out.write("            color: #ffffff;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn_group .resbtn {\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            background-color: #ffffff;\r\n");
      out.write("            color: #222222;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("        }        \r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<header id=\"header\">\r\n");
      out.write("    <div class=\"header_wrap\">\r\n");
      out.write("        <div class=\"header_top\">\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/top_banner.jpg\" alt=\"top_banner\">\r\n");
      out.write("                <button type=\"button\" class=\"btn-close btn-close-white\" aria-label=\"Close\"></button>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div> \r\n");
      out.write("        <div class=\"header_container\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("                <div class=\"textbox_wrap\">\r\n");
      out.write("                    <div class=\"textbox\">G</div>\r\n");
      out.write("                    <div class=\"textbox\">M</div>\r\n");
      out.write("                    <div class=\"textbox\">O</div>\r\n");
      out.write("                    <div class=\"textbox\">V</div>\r\n");
      out.write("                    <div class=\"textbox\">I</div>\r\n");
      out.write("                    <div class=\"textbox\">E</div>\r\n");
      out.write("                    <div class=\"textbox2\">절찬상영중</div>                 \r\n");
      out.write("                </div> \r\n");
      out.write("            </a>          \r\n");
      out.write("            <div  class=\"left_link\">\r\n");
      out.write("                <a href=\"#\"><i class=\"xi-facebook-official xi-x\"></i>페이스북</a>\r\n");
      out.write("                <a href=\"#\"><i class=\"xi-youtube-play xi-x\"></i>유튜브</a>\r\n");
      out.write("                <a href=\"#\"><i class=\"xi-instagram xi-x\"></i>인스타그램</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"right_link\">\r\n");
      out.write("            <!-- 로그인 전 -->\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            <!-- 로그인 후 --> \r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            <!-- 관리자 로그인 일 때 -->\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </div>           \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"topMenu\">\r\n");
      out.write("        <ul class=\"menu01\">\r\n");
      out.write("            <li><span>예매</span>\r\n");
      out.write("                <ul class=\"dept01\">\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">예매하기</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">상영시간표</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">할인안내</a></li>\r\n");
      out.write("                    \r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class=\"menu01\">\r\n");
      out.write("            <li><span>영화</span>\r\n");
      out.write("                <ul class=\"dept01\">\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">홈</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">현재상영작</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">상영예정작</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class=\"menu01\">\r\n");
      out.write("            <li><span>영화관</span>\r\n");
      out.write("                <ul class=\"dept01\">\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">스페셜관</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">서울</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">경기/인천</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class=\"menu01\">\r\n");
      out.write("            <li><span>이벤트</span>\r\n");
      out.write("                <ul class=\"dept01\">\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">홈</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">시사회/무대인사</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">제휴할인</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class=\"menu01\">\r\n");
      out.write("            <li><span>스토어</span>\r\n");
      out.write("                <ul class=\"dept01\">\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">베스트</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">관람권</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">스낵음료</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"none\">\r\n");
      out.write("    </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <script>\r\n");
      out.write("        jQuery(document).ready(function($) {\r\n");
      out.write("            $(\"#navigation-list\").hide();\r\n");
      out.write("            $(\".menuBtn\").click(function() {\r\n");
      out.write("                $(\"#navigation-list\").slideToggle(300);\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        $(document).on('mouseover', '.topMenu span', function() {\r\n");
      out.write("        $('.dept01').slideDown(500);\r\n");
      out.write("        });\r\n");
      out.write("        $(document).on('mouseover', 'div', function () {\r\n");
      out.write("        if (!$(this).hasClass('topMenu')) {\r\n");
      out.write("            $('.dept01').slideUp(500);\r\n");
      out.write("        }\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("        <div class=\"agreement\">\r\n");
      out.write("            <h2>개인회원 약관동의</h2>\r\n");
      out.write("            <p>GMOVIE 회원으로 가입하기 위해서는 이용약관,개인정보처리방침에 동의하셔야 합니다.</p>\r\n");
      out.write("            <h4 class=\"mt20\">이용약관</h4>\r\n");
      out.write("            <div class=\"agreeBox\">\r\n");
      out.write("                <div>\r\n");
      out.write("                비회원 예매 서비스 이용약관\r\n");
      out.write("\r\n");
      out.write("                제 1 조 (목적)\r\n");
      out.write("                이 약관은 GMOVIE (주)(이하 \"회사\"라 함)가 제공하는 인터넷 서비스(이하\"서비스\"라 함)의 이용과 관련하여 \"회사\"와 \"비회원\" 이용자와의 권리, 의무 및 책임사항, 기타 필요한 사항을 규정함을 목적으로 합니다.\r\n");
      out.write("\r\n");
      out.write("                제 2 조 (정의)\r\n");
      out.write("                이 약관에서 사용하는 용어의 정의는 다음과 같습니다.\r\n");
      out.write("                1) \"서비스\"라 함은, \"회사\"가 비회원 이용자가 PC, 단말기(휴대형 단말기 등의 각종 유무선 장치)를 이용하여 CGV극장 정보를 이용할 수 있도록, 영화정보 제공, 결제 등의 편의를 제공하는 것을 의미합니다.\r\n");
      out.write("                2) \"고객인증번호\"라 함은, 사용자의 이름, 휴대폰번호, 법정생년월일[6자리], 비밀번호를 이용하여 개인을 확인할 수 있는 정보를 말합니다.\r\n");
      out.write("                3) \"이용자\"이라 함은, CGV에 회원으로 가입하지 아니하고, \"고객인증번호\"를 이용하여 회사와 이용계약을 체결하고 \"회사\"가 제공하는 제한적인 \"서비스\"를 이용하는 고객을 말합니다.\r\n");
      out.write("\r\n");
      out.write("                제 3 조 (약관의 게시와 개정)\r\n");
      out.write("                1) \"회사\"는 약관의규제에관한법률, \"정보통신망이용촉진및정보보호등에관한법률(이하 \"정보통신망법\")\" 등 관련 법을 위배하지 않는 범위에서 본 약관을 개정할 수 있습니다.\r\n");
      out.write("                2) \"회사\"가 본 약관을 개정할 경우에는, 적용일자 및 개정사유를 명시하여 현행 약관과 함께 관련법률에 따라 그 개정 약관의 적용일자 30일 전부터 적용일자 전일까지 공지합니다. 다만, \"이용자\"에게 불리한 약관의 개정의 경우에는 팝업공지로 명확히 통지하도록 합니다.\r\n");
      out.write("                3) \"회사\"가 전항에 따라 개정약관을 팝업 공지로 통지하고 동의 또는 거부 버튼을 활성화 시키며, \"이용자\"는 동의 또는 거부 버튼을 눌러서 서비스 이용 여부를 결정할 수 있습니다.\r\n");
      out.write("                4) \"이용자\"가 개정약관의 적용에 동의하지 않는 경우, \"회사\"는 개정약관의 내용을 적용할 수 없으며, 이 경우 \"이용자\"는 본 \"서비스\"를 이용하지 못합니다 .\r\n");
      out.write("\r\n");
      out.write("                제 4 조 (약관의 해석)\r\n");
      out.write("                1) \"회사\"는 개별 서비스에 대해서는 별도의 이용약관 및 정책(이하 \"유료서비스약관 등\"라 함)을 둘 수 있으며, 이 약관과 상충할 경우에는, 해당 약관의 내용이 우선하여 적용됩니다.\r\n");
      out.write("                2) 이 약관에서 정하지 아니한 사항이나 해석에 대해서는 관계법령 또는 상관례에 따릅니다.\r\n");
      out.write("\r\n");
      out.write("                제 5 조 (이용계약 체결)\r\n");
      out.write("                1) 이용계약은, \"이용자\"가 \"서비스\"를 이용하고자 하는 경우 체결하는 것으로, 이 약관의 내용에 대하여 동의함을 표시한 다음 고객인증번호(이름, 휴대폰번호, 법정생년월일[6자리], 비밀번호)를 입력하면 이용신청절차가 완료되며, \"회사\"가 이러한 이용신청 절차에 대하여 승낙하면 이용계약체결이 완료됩니다.\r\n");
      out.write("                2) \"회사\"는 고객이 이용신청에 대하여 승낙함을 원칙으로 합니다. 다만, \"회사\"는 다음 각 호에 해당하는 신청에 대하여는 승낙을 하지 않거나 사후에 이용계약을 해지할 수 있습니다.\r\n");
      out.write("                가) 이용 신청자가 이 약관에 의하여 이전에 \"이용자\"자격을 상실한 적이 있는 경우, 단 \"회사\"의 \"이용자\" 승낙을 얻은 경우에는 예외로 함.\r\n");
      out.write("                나) 타인의 명의를 이용한 경우\r\n");
      out.write("                다) 허위의 정보를 기재하거나, \"회사\"가 제시하는 내용을 기재하지 않은 경우\r\n");
      out.write("                라) 14세 미만 아동이 법정대리인(부모 등)의 동의를 얻지 아니한 경우\r\n");
      out.write("                마) \"이용자\"의 귀책사유로 인하여 승인이 불가능하거나 기타 규정한 제반 사항을 위반하며 신청하는 경우\r\n");
      out.write("                3) \"회사\"는 서비스 관련 설비의 여유가 없거나, 기술상 또는 업무상 문제가 있는 경우에는 승낙을 유보할 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("                제 6 조 (개인정보보호 의무)\r\n");
      out.write("                \"회사\"는 \"정보통신망법\" 등 관계법령이 정하는 바에 따라, \"이용자\"의 개인정보를 보호하기 위해 노력합니다. 개인정보의 보호 및 사용에 대해서는 관련법 및 \"회사\"의 개인정보취급방침이 적용됩니다.\r\n");
      out.write("\r\n");
      out.write("                제 7 조 (\"이용자\"의 \"고객인증번호\" 의 관리에 대한 의무)\r\n");
      out.write("                1) \"이용자\"의 고객인증번호(이름, 휴대폰번호, 법정생년월일[6자리], 비밀번호)에 관한 관리책임은 \"서비스\" 이용자 본인에게 있으며, 이를 제 3자가 이용하도록 하여서는 안 됩니다.\r\n");
      out.write("                2) \"회사\"는 \"이용자\"의 \"고객인증번호\"가 개인정보 유출 우려가 있거나, 반사회적 또는 미풍양속에 어긋나거나 \"회사\" 및 \"회사\"의 운영자로 오인할 우려가 있는 경우, 해당 \"고객인증번호\"의 이용을 제한할 수 있습니다.\r\n");
      out.write("                3) \"이용자\"는 \"고객인증번호\"가 도용되거나 제3자가 사용하고 있음을 인지한 경우에는, 이를 즉시 \"회사\"에 통지하고 \"회사\"의 안내에 따라야 합니다.\r\n");
      out.write("                4) 제 3)항의 경우에 해당 \"이용자\"가 \"회사\"에 그 사실을 통지하지 않거나, 통지한 경우에도 \"회사\"의 안내에 따르지 않아 발생한 불이익에 대하여 \"회사\"는 책임지지 않습니다.\r\n");
      out.write("\r\n");
      out.write("                제 8 조 (\"이용자\"에 대한 통지)\r\n");
      out.write("                \"회사\"는 \"이용자\"에 대한 통지의 경우, 서비스 내 공지사항 화면에 게시함으로써 개별 통지에 갈음합니다.\r\n");
      out.write("\r\n");
      out.write("                제 9 조 (\"회사\"의 의무)\r\n");
      out.write("                1) \"회사\"는 관련법과 이 약관이 금지하거나 미풍양속에 반하는 행위를 하지 않으며, 계속적이고 안정적인 \"서비스\"를 제공하기 위하여 최선을 다하여 노력합니다.\r\n");
      out.write("                2) \"회사\"는 \"이용자\"가 안전하게 \"서비스\"를 이용할 수 있도록 개인정보(신용정보 포함)보호를 위해 보안시스템을 갖추어야 하며 개인정보취급방침을 공시하고 준수합니다.\r\n");
      out.write("                3) \"회사\"는 \"서비스\" 이용과 관련하여 \"이용자\"로부터 제기된 의견이나 불만이 정당하다고 인정할 경우에는 이를 처리하여야 합니다. \"이용자\"가 제기한 의견이나 불만사항에 대해서는 게시판 혹은 별도의 연락수단을 활용하여 \"이용자\"에게 처리과정 및 결과를 전달합니다.\r\n");
      out.write("\r\n");
      out.write("                제 10 조 (\"비회원\"의 의무)\r\n");
      out.write("                1) \"이용자\"는 다음 행위를 하여서는 안 됩니다.\r\n");
      out.write("                가) 신청 또는 변경 시 허위내용의 등록\r\n");
      out.write("                나) 타인의 정보도용\r\n");
      out.write("                다) \"회사\"가 게시한 정보의 변경\r\n");
      out.write("                라) 타인의 개인정보 및 계정정보를 수집하는 행위\r\n");
      out.write("                마) \"회사\"의 사전동의 없이 영리 목적의 광고성 정보를 전송하기 위하여 이용하는 행위\r\n");
      out.write("                바) 리버스 엔지니어링, 디컴파일, 디스어셈블 및 기타 일체의 가공행위를 통하여 \"서비스\"를 복제, 분해 또는 모방 기타 변형하는 행위\r\n");
      out.write("                사) 자동 접속 프로그램 등을 사용하는 등 정상적인 용법과 다른 방법으로 \"서비스\"를 이용하여 \"회사\"의 서버에 부하를 일으켜 회사의 정상적인 \"서비스\"를 방해하는 행위\r\n");
      out.write("                아) 본인 아닌 제3자에게 접속권한을 부여하는 행위\r\n");
      out.write("                자) \"회사\"와 기타 제 3자의 저작권 등 지적재산권에 대한 침해\r\n");
      out.write("                차) \"회사\" 및 기타 제3자의 명예를 손상시키거나 업무를 방해하는 행위\r\n");
      out.write("                카) 외설 또는 폭력적인 메시지, 화상, 음성, 기타 공서양속에 반하는 정보를 \"서비스\"에 공개 또는 게시하는 행위\r\n");
      out.write("                타) \"회사\"의 동의없이 영리를 목적으로 \"서비스\"를 사용하는 행위\r\n");
      out.write("                파) 기타 불법적이거나 부당한 행위\r\n");
      out.write("                2) \"이용자\"는 관계법, 이 약관의 규정, 이용안내 및 \"서비스\"와 관련하여 공지한 주의사항, \"회사\"가 통지하는 사항 등을 준수하여야 하며, 기타 \"회사\"의 업무에 방해되는 행위를 하여서는 안 됩니다.\r\n");
      out.write("\r\n");
      out.write("                제 11 조 (\"서비스\"의 제공 등)\r\n");
      out.write("                1) \"회사\"는 \"이용자\"에게 아래와 같은 서비스를 제공합니다.\r\n");
      out.write("                가) 영화정보(현재상영작, 상영예정작, 영화상세정보, 영화인물정보)\r\n");
      out.write("                나) CGV 영화예매 서비스\r\n");
      out.write("                다) CGV 극장 상영시간표\r\n");
      out.write("                라) MY CGV\r\n");
      out.write("                마) 기타 \"회사\"가 추가 개발하거나 다른 회사와의 제휴계약 등을 통해 \"이용자\"에게 제공하는 일체의 서비스를 의미하며 단, \"회원\"이 이용하는 \"리뷰쓰기\" 및 제휴결제수단 이용이 불가합니다.\r\n");
      out.write("                2) \"회사\"는 \"서비스\"를 일정범위로 분할하여 각 범위 별로 이용가능시간을 별도로 지정할 수 있습니다. 다만, 이러한 경우에는 그 내용을 사전에 공지합니다.\r\n");
      out.write("                3) \"서비스\"는 연중무휴, 1일 24시간 제공함을 원칙으로 합니다.\r\n");
      out.write("                4) \"회사\"는 컴퓨터 등 정보통신설비의 보수점검, 교체 및 고장, 통신두절 또는 운영상 상당한 이유가 있는 경우 \"서비스\"의 제공을 일시적으로 중단할 수 있습니다. 이 경우 \"회사\"는 제8조[\"이용자\"에 대한 통지]에 정한 방법으로 \"이용자\"에게 통지합니다. 다만, \"회사\"가 사전에 통지할 수 없는 부득이한 사유가 있는 경우 사후에 통지할 수 있습니다.\r\n");
      out.write("                5) \"회사\"는 \"서비스\"의 제공에 필요한 경우, 정기점검을 실시할 수 있으며, 정기점검시간은 \"서비스\" 제공화면에 공지한 바에 따릅니다.\r\n");
      out.write("\r\n");
      out.write("                제 12 조 (\"서비스\"의 변경)\r\n");
      out.write("                1) \"회사\"는 이용 감소로 인한 원활한 \"서비스\" 제공의 곤란 및 수익성 악화, 기술 진보에 따른 차세대 \"서비스\"로의 전환 필요성, \"서비스\" 제공과 관련한 \"회사\"의 정책의 변경 등 기타 상당한 이유가 있는 경우에 운영상, 기술상의 필요에 따라 제공하고 있는 전부 또는 일부 \"서비스\"를 변경 또는 중단할 수 있습니다.\r\n");
      out.write("                2) \"회사\"는 무료로 제공되는 \"서비스\"의 일부 또는 전부를 \"회사\"의 정책 및 운영의 필요상 수정, 중단, 변경할 수 있으며, 이에 대하여 관련법에 특별한 규정이 없는 한 \"이용자\"에게 별도의 보상을 하지 않습니다.\r\n");
      out.write("                3) \"서비스\"의 내용, 이용방법, 이용시간에 대하여 변경 또는 \"서비스\" 중단이 있는 경우에는 변경 또는 중단될 \"서비스\"의 내용 및 사유와 일자 등은 그 변경 또는 중단 전에 \"회사\" 웹사이트 또는 \"서비스\" 내 공지사항 화면, SMS등 \"이용자\"가 충분이 인지할 수 있는 방법으로 사전에 공지합니다.\r\n");
      out.write("\r\n");
      out.write("                제 13 조 (정보의 제공 및 광고의 게재)\r\n");
      out.write("                1) \"회사\"가 \"이용자\"에게 \"서비스\"를 제공할 수 있는 \"서비스\" 투자기반의 일부는 광고게재를 통한 수익으로부터 나옵니다. \"서비스\"를 이용하고자 하는 자는 \"서비스\" 이용 시 노출되는 광고 게재에 대해 동의하는 것으로 간주됩니다.\r\n");
      out.write("                2) \"회사\"는 \"서비스\" 상에 게재되어 있거나 \"서비스\"를 통한 광고주의 판촉활동에 \"이용자\"가 참여하거나 교신 또는 거래의 결과로서 발생하는 모든 손실 또는 손해에 대해 책임을 지지 않습니다.\r\n");
      out.write("\r\n");
      out.write("                제 14 조 (권리의 귀속)\r\n");
      out.write("                1) \"서비스\"에 대한 저작권 및 지적재산권은 \"회사\"에 귀속됩니다.\r\n");
      out.write("                2) \"회사\"가 제공하는 \"서비스\"의 디자인, \"회사\"가 만든 텍스트, 스크립트(script), 그래픽, \"이용자\" 상호간 전송 기능 등 \"회사\"가 제공하는 \"서비스\"에 관련된 모든 상표, 서비스 마크, 로고 등에 관한 저작권 기타 지적재산권은 대한민국 및 외국의 법령에 기하여 \"회사\"가 보유하고 있거나 \"회사\"에게 소유권 또는 사용권이 있습니다.\r\n");
      out.write("                3) \"이용자\"은 본 이용약관으로 인하여 \"서비스\"를 소유하거나 \"서비스\"에 관한 저작권을 보유하게 되는 것이 아니라, \"회사\"로부터 \"서비스\"의 이용을 허락 받게 되는바, \"서비스\"는 정보취득 또는 개인용도로만 제공되는 형태로 \"이용자\"가 이용할 수 있습니다.\r\n");
      out.write("                4) \"이용자\"는 명시적으로 허락된 내용을 제외하고는 \"서비스\"를 통해 얻어지는 \"이용자\" 상태정보를 영리 목적으로 사용, 복사, 유통하는 것을 포함하여 \"회사\"가 만든 텍스트, 스크립트, 그래픽의 \"비회원\" 상호간 전송기능 등을 복사하거나 유통할 수 없습니다.\r\n");
      out.write("                5) \"회사\"는 \"서비스\"와 관련하여 \"이용자\"에게 \"회사\"가 정한 이용조건에 따라 콘텐츠 등을 이용할 수 있는 이용권만을 부여하며, \"이용자\"는 이를 양도, 판매, 담보제공 등의 처분행위를 할 수 없습니다.\r\n");
      out.write("\r\n");
      out.write("                제 15 조 (\"이용자\" 정보 삭제)\r\n");
      out.write("                \"회사\"는 예매확인 및 취소를 위해 \"이용자\"의 \"고객인증번호\"를 보유하며, 이 외의 경우 관련법 및 \"개인정보 수집 및 이용안내\"에 따라 모든 데이터는 소멸됩니다.\r\n");
      out.write("\r\n");
      out.write("                제 16 조 (이용제한 등)\r\n");
      out.write("                1) \"회사\"는 \"이용자\"가 이 약관의 의무를 위반하거나 \"서비스\"의 정상적인 운영을 방해한 경우, 경고, 일시정지, 영구이용정지 등으로 \"서비스\" 이용을 단계적으로 제한할 수 있습니다.\r\n");
      out.write("                2) \"회사\"는 전항에도 불구하고, 명의도용 및 결제도용, 전화번호 도용, 저작권법 및 컴퓨터프로그램보호법을 위반한 불법프로그램의 제공 및 운영방해, \"정보통신망법\"을 위반한 불법통신 및 해킹, 악성프로그램의 배포, 접속권한 초과행위 등과 같이 관련법을 위반한 경우에는, 즉시 영구이용정지를 할 수 있습니다. 본 항에 따른 영구이용정지 시 \"서비스\" 이용을 통해 획득한 혜택 등도 모두 소멸되며, \"회사\"는 이에 대해 별도로 보상하지 않습니다.\r\n");
      out.write("                3) 본 조에 따라 \"서비스\" 이용을 제한하거나 계약을 해지하는 경우 \"회사\"는 제 7조 [\"이용자\"에 대한 통지]에 따라 통지합니다.\r\n");
      out.write("\r\n");
      out.write("                제 17 조 (결제서비스 제한)\r\n");
      out.write("                \"이용자\"는 다음의 결제 서비스만 이용 가능합니다.\r\n");
      out.write("                1) 신용카드 결제 : 신용카드 정보 입력 후 사용\r\n");
      out.write("\r\n");
      out.write("                제 18 조 (서비스 제공의 중지 등)\r\n");
      out.write("                1) \"회사\"는 다음 각 호에 해당하는 경우 \"서비스\" 제공을 중지할 수 있습니다.\r\n");
      out.write("                가) \"서비스\"용 설비의 보수 등 공사로 인한 부득이한 경우\r\n");
      out.write("                나) 전기통신사업법에 규정된 기간통신사업자가 전기통신서비스를 중지했을 경우\r\n");
      out.write("                다) 기타 불가항력적 사유가 있는 경우\r\n");
      out.write("                2) \"회사\"는 국가비상사태, 정전, \"서비스\" 설비의 장애 또는 \"서비스\" 이용의 폭주 등으로 정상적인 \"서비스\" 이용에 지장이 있는 때에는 \"서비스\"의 전부 또는 일부를 제한하거나 중지할 수 있습니다.\r\n");
      out.write("                3) \"회사\"는 제 1항 및 제 2항의 규정에 의하여 \"서비스\"의 이용을 제한하거나 중지한 때에는 그 사유 및 제한기간 등을 지체 없이 회원에게 알려야 합니다.\r\n");
      out.write("\r\n");
      out.write("                제 19 조 (면책조항)\r\n");
      out.write("                1) \"회사\"는 천재지변 또는 이에 준하는 불가항력으로 인하여 \"서비스\"를 제공할 수 없는 경우에는, \"서비스\" 제공에 관한 책임이 면제됩니다.\r\n");
      out.write("                2) \"회사\"는 \"이용자\"의 귀책사유 또는 PC, 단말기(휴대형 단말기 등의 각종 유무선 장치)의 장애로 인한 \"서비스\" 이용의 장애에 대하여 책임을 지지 않습니다.\r\n");
      out.write("                3) \"회사\"는 \"이용자\"가 \"서비스\"를 이용하여 기대하는 수익을 상실했거나, 혹은 \"서비스\"를 통하여 얻은 자료로 인한 손해에 관하여 책임을 지지 않습니다.\r\n");
      out.write("                4) \"회사\"는 \"서비스\"에 게재한 정보, 자료, 사실의 신뢰도, 정확성 등 내용에 관하여는 책임을 지지 않습니다.\r\n");
      out.write("\r\n");
      out.write("                제 20 조 (해외이용)\r\n");
      out.write("                1) \"회사\"는 대한민국 내에 설치된 서버를 기반으로 \"서비스\"를 제공 및 관리하고 있습니다. 따라서 \"회사\"는 \"이용자\"가 대한민국의 영토 이외의 지역에서 \"서비스\"를 이용하고자 하는 경우 \"서비스\"의 품질 또는 사용성을 보장하지 않습니다.\r\n");
      out.write("                2) \"이용자\"는 대한민국의 영토 이외의 지역에서 \"서비스\"를 이용하고자 하는 경우 스스로의 판단과 책임에 따라서 이용 여부를 결정하여야 하고, 특히 \"서비스\"의 이용과정에서 현지 법령을 준수할 책임은 \"이용자\"에게 있습니다.\r\n");
      out.write("\r\n");
      out.write("                제 21 조 (준거법 및 재판관할)\r\n");
      out.write("                1) \"회사\"와 \"이용자\"간 제기된 소송은 대한민국법을 준거법으로 합니다.\r\n");
      out.write("                2) \"회사\"와 \"이용자\"간 발생한 분쟁에 대해서는 서울중앙지방법원을 합의 관할법원으로 합니다.\r\n");
      out.write("\r\n");
      out.write("                - 끝 -\r\n");
      out.write("                </div>\r\n");
      out.write("                <p><input type=\"checkbox\" id=\"chk1\" name=\"agree\"><label for=\"chk1\">위의 <span class=\"blueText\">이용약관</span>에 동의합니다.</label></p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <h4 class=\"mt20\">개인정보처리방침</h4>\r\n");
      out.write("            <div class=\"agreeBox\">\r\n");
      out.write("                <div>\r\n");
      out.write("                가. 개인정보의 수집 및 이용 목적\r\n");
      out.write("                ① GMOVIE는 다음의 목적을 위하여 개인정보를 처리합니다. 처리하고 있는 개인정보는 다음의 목적 이외의 용도로는 이용되지 않으며, 이용 목적이 변경되는 경우에는 개인정보 보호법 제18조에 따라 별도의 동의를 받는 등 필요한 조치를 이행할 예정입니다.\r\n");
      out.write("                1. GMOVIE 서비스 제공을 위한 회원관리\r\n");
      out.write("                1) 공간정보 다운로드, 오픈API 신청 및 활용 등 포털 서비스 제공과 서비스 부정이용 방지를 목적으로 개인정보를\r\n");
      out.write("                처리합니다.\r\n");
      out.write("\r\n");
      out.write("                나. 정보주체와 법정대리인의 권리ㆍ의무 및 행사방법\r\n");
      out.write("                ① 정보주체(만 14세 미만인 경우에는 법정대리인을 말함)는 언제든지 개인정보 열람·정정·삭제·처리정지 요구 등의 권리를 행사할 수 있습니다.\r\n");
      out.write("                ② 제1항에 따른 권리 행사는 개인정보보호법 시행규칙 별지 제8호 서식에 따라 작성 후 서면, 전자우편 등을 통하여 하실 수 있으며, 기관은 이에 대해 지체 없이 조치하겠습니다.\r\n");
      out.write("                ③ 제1항에 따른 권리 행사는 정보주체의 법정대리인이나 위임을 받은 자 등 대리인을 통하여 하실 수 있습니다. 이 경우 개인정보 보호법 시행규칙 별지 제11호 서식에 따른 위임장을 제출하셔야 합니다.\r\n");
      out.write("                ④ 개인정보 열람 및 처리정지 요구는 개인정보 보호법 제35조 제5항, 제37조 제2항에 의하여 정보주체의 권리가 제한 될 수 있습니다.\r\n");
      out.write("                ⑤ 개인정보의 정정 및 삭제 요구는 다른 법령에서 그 개인정보가 수집 대상으로 명시되어 있는 경우에는 그 삭제를 요구할 수 없습니다.\r\n");
      out.write("                ⑥ 정보주체 권리에 따른 열람의 요구, 정정ㆍ삭제의 요구, 처리정지의 요구 시 열람 등 요구를 한 자가 본인이거나 정당한 대리인인지를 확인합니다.\r\n");
      out.write("\r\n");
      out.write("                다. 수집하는 개인정보의 항목\r\n");
      out.write("                ① GMOVIE 회원정보(필수): 이름, 이메일(아이디), 비밀번호\r\n");
      out.write("\r\n");
      out.write("                라. 개인정보의 보유 및 이용기간\r\n");
      out.write("                ① GMOVIE 법령에 따른 개인정보 보유ㆍ이용기간 또는 정보주체로부터 개인정보를 수집 시에 동의 받은 개인정보 보유ㆍ이용기간 내에서 개인정보를 처리ㆍ보유합니다.\r\n");
      out.write("                1. GMOVIE 회원정보\r\n");
      out.write("                - 수집근거: 정보주체의 동의\r\n");
      out.write("                - 보존기간: 회원 탈퇴 요청 전까지(1년 경과 시 재동의)\r\n");
      out.write("                - 보존근거: 정보주체의 동의\r\n");
      out.write("\r\n");
      out.write("                마. 동의 거부 권리 및 동의 거부에 따른 불이익\r\n");
      out.write("                위 개인정보의 수집 및 이용에 대한 동의를 거부할 수 있으나, 동의를 거부할 경우 회원 가입이 제한됩니다.\r\n");
      out.write("                </div>\r\n");
      out.write("                <p><input type=\"checkbox\" id=\"chk1\" name=\"agree\"><label for=\"chk1\">위의 <span class=\"blueText\">개인정보 수집및 이용에 대한 안내</span>에 동의합니다.</label></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"all_agreement\">\r\n");
      out.write("                <p class=\"join_agreement\"><input type=\"checkbox\" id=\"chk2\" name=\"all_agree\"><label for=\"chk2\">위의 <span class=\"blueText\">이용약관 및 개인정보 수집 및 이용에 대한 안내</span>에 동의합니다.</label></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"btn_group\">\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/joinForm.do\"><button type=\"submit\" class=\"subbtn\" onclick=\"chk()\">확인</button></a>\r\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\"><button type=\"reset\" class=\"resbtn\" onclick=\"unchk()\">취소</button></a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<footer id=\"footer\">\r\n");
      out.write("<div class=\"footer_wrap\">\r\n");
      out.write("    <div class=\"footer_top\">\r\n");
      out.write("        <ul class=\"fnb\">\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/gmovieInfo.do\">회사소개</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/recruit.do\">인재채용</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/social.do\">사회공헌</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/partner.do\">제휴/광고/부대사업문의</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/rules.do\">법적고지</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/emreject.do\">이메일주소무단수집거부</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/management.do\">윤리경영</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer_bottom\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/footer_logo.png\" alt=\"푸터로고\" class=\"footerLogo\">\r\n");
      out.write("        <span>\r\n");
      out.write("            <strong>주소 : 경기도 시흥시 은계번영길 9, 4F 409~411(은행동 골드웨이)</strong>                   \r\n");
      out.write("        </span>\r\n");
      out.write("        <span>\r\n");
      out.write("            <strong>E-mail : </strong>\r\n");
      out.write("                gmovie@naver.com\r\n");
      out.write("        </span>\r\n");
      out.write("        <br>\r\n");
      out.write("        <span>\r\n");
      out.write("            <strong>상호명 : </strong>\r\n");
      out.write("                GMOVIE\r\n");
      out.write("        </span>\r\n");
      out.write("        <span>\r\n");
      out.write("            <strong>대표이사 : </strong>\r\n");
      out.write("                이규진\r\n");
      out.write("        </span>\r\n");
      out.write("        <span>\r\n");
      out.write("            <strong>사업자등록번호 : </strong>\r\n");
      out.write("            647-16-02021\r\n");
      out.write("        </span>\r\n");
      out.write("        <span>\r\n");
      out.write("            <strong>통신판매업신고번호 : </strong>\r\n");
      out.write("                2022-경기시흥-1113\r\n");
      out.write("        </span>\r\n");
      out.write("        <p>COPYRIGHT ⓒ2022 GMOVIE All right Reserved</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</footer>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        // 전체 선택, 전체 해제\r\n");
      out.write("       $(\".agreement\").on(\"click\", \"#chk2\", function() {\r\n");
      out.write("            var checked = $(this).is(\":checked\");\r\n");
      out.write("\r\n");
      out.write("            if(checked) {\r\n");
      out.write("                $(this).parents(\".agreement\").find('input').prop(\"checked\", true);\r\n");
      out.write("            } else {\r\n");
      out.write("                $(this).parents(\".agreement\").find('input').prop(\"checked\", false);\r\n");
      out.write("            }\r\n");
      out.write("       });\r\n");
      out.write("\r\n");
      out.write("       $(\".agreement\").on(\"click\", \"#chk1\", function() {\r\n");
      out.write("            var checked = $(this).is(\":checked\");\r\n");
      out.write("\r\n");
      out.write("            if(!checked) {\r\n");
      out.write("                $(\"#chk2\").prop(\"checked\", false);\r\n");
      out.write("            }\r\n");
      out.write("       });\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/member/agreement.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path1");
      // /WEB-INF/views/member/agreement.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/agreement.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/member/../include/header.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("path1");
      // /WEB-INF/views/member/../include/header.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/../include/header.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/member/../include/header.jsp(33,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sid }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/loginForm.do\">\r\n");
          out.write("                    <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/imgs/loginPassword.png\" alt=\"\">\r\n");
          out.write("                    		로그인\r\n");
          out.write("                </a>\r\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/agreement.do\">\r\n");
          out.write("                    <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/imgs/loginJoin.png\" alt=\"\">\r\n");
          out.write("                   		 	회원가입\r\n");
          out.write("                </a>\r\n");
          out.write("                <a href=\"#\">\r\n");
          out.write("                    <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/imgs/loginCustomer.png\" alt=\"\">\r\n");
          out.write("                   			 고객센터\r\n");
          out.write("                </a>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/member/../include/header.jsp(48,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sid }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<span style=\"font-weight: bold; font-size: 1.3em\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님</span>\r\n");
          out.write("            	<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/read.do\">마이페이지</a>\r\n");
          out.write("            	<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/logout.do\">로그아웃</a>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/member/../include/header.jsp(54,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sid == 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("       \r\n");
          out.write("                <button type=\"button\" class=\"menuBtn\">\r\n");
          out.write("                    <i class=\"xi-bars xi-x\"></i>\r\n");
          out.write("                    <nav id=\"navigation-list\" class=\"navList\">\r\n");
          out.write("                        <ul>\r\n");
          out.write("                            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/list.do\">회원 목록</a></li>\r\n");
          out.write("                            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/board/list.do\">게시판 목록</a></li>\r\n");
          out.write("                            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/board/writeForm.do\">게시판 등록</a></li>\r\n");
          out.write("                        </ul>\r\n");
          out.write("                    </nav>\r\n");
          out.write("                </button>\r\n");
          out.write("             ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/member/../include/footer.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("path1");
      // /WEB-INF/views/member/../include/footer.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/../include/footer.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }
}
