/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-08-26 04:39:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/gyujin/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/gmovie/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/gyujin/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/gmovie/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1659671595531L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>회원가입</title>\r\n");
      out.write("    <script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100&display=swap');\r\n");
      out.write("    * {margin: 0; padding: 0; box-sizing: border-box;}\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        background: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/moon-g8471bddc6_1920.jpg) no-repeat center;\r\n");
      out.write("        background-size: cover;\r\n");
      out.write("    }\r\n");
      out.write("    body::before {\r\n");
      out.write("        content: \"\";\r\n");
      out.write("        position: absolute; z-index: 1;\r\n");
      out.write("        top: 0; right: 0; bottom: 0; left: 0;\r\n");
      out.write("        background-color: rgba(0, 0, 0, 0.7);\r\n");
      out.write("    }\r\n");
      out.write("    .join-form {position: relative; z-index: 2;}\r\n");
      out.write("    .join-form h1 {\r\n");
      out.write("        font-size: 32px; color: #fff;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("        padding-top: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    .int-area {width: 400px; position: relative; margin-top: 20px;}\r\n");
      out.write("    .int-area:first-child{margin-top: 0;}\r\n");
      out.write("    .int-area input {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 20px 10px 10px;\r\n");
      out.write("        background-color: transparent;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-bottom:1px solid #999;\r\n");
      out.write("        font-size:18px; color: #fff;\r\n");
      out.write("        outline: none;\r\n");
      out.write("    }\r\n");
      out.write("    .int-area label {\r\n");
      out.write("        position: absolute; left: 10px; top: 15px;\r\n");
      out.write("        font-size: 18px; color: #999;\r\n");
      out.write("        transition: all .5s ease;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .int-area label.warning {\r\n");
      out.write("        color: red; !important;\r\n");
      out.write("        animation: warning .3s ease;\r\n");
      out.write("        animation-iteration-count: 3;\r\n");
      out.write("    }\r\n");
      out.write("    @keyframes warning {\r\n");
      out.write("        0% {transform:  translateX(-8px);}\r\n");
      out.write("        25% {transform:  translateX(8px);}\r\n");
      out.write("        50% {transform:  translateX(-8px);}\r\n");
      out.write("        75% {transform:  translateX(8px);}\r\n");
      out.write("    }\r\n");
      out.write("    .int-area input:focus + label,\r\n");
      out.write("    .int-area input:valid + label {\r\n");
      out.write("        top: -2px;\r\n");
      out.write("        font-size: 13px; color: #166cea;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .btn-area {margin-top: 30px;}\r\n");
      out.write("    .btn-area button {\r\n");
      out.write("        width: 100%; height: 50px;\r\n");
      out.write("        background-color: #166cea;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 25px;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    .caption {\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .caption a {\r\n");
      out.write("        font-size: 15px; color: #999;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .id_ok {\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .id_already {\r\n");
      out.write("        color: red;\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("    </style>\r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <section class=\"join-form\">\r\n");
      out.write("        <h1>JOIN</h1>\r\n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/join.do\" method=\"post\" onsubmit=\"return joinCheck(this)\" name=\"joinForm\">\r\n");
      out.write("            <div class=\"int-area\">\r\n");
      out.write("                <input type=\"text\" name=\"userid\" id=\"userid\" autocomplete=\"off\" maxlength=\"20\" required oninput=\"idCheck()\">\r\n");
      out.write("                <label for=\"userid\">ID</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <span class=\"id_ok\">사용 가능한 아이디 입니다.</span>\r\n");
      out.write("			<span class=\"id_already\">이미 사용중인 아이디 입니다.</span>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <div class=\"int-area\">\r\n");
      out.write("                <input type=\"password\" name=\"userpw\" id=\"userpw\" autocomplete=\"off\" required>\r\n");
      out.write("                <label for=\"userpw\">PASSWORD</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"int-area\">\r\n");
      out.write("                <input type=\"password\" name=\"userpw2\" id=\"userpw2\" autocomplete=\"off\" required>\r\n");
      out.write("                <label for=\"userpw2\">Confirm Password</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"int-area\">\r\n");
      out.write("                <input type=\"text\" name=\"username\" id=\"username\" autocomplete=\"off\" required>\r\n");
      out.write("                <label for=\"username\">USER NAME</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"int-area\">\r\n");
      out.write("                <input type=\"tel\" name=\"tel\" id=\"tel\" autocomplete=\"off\" required>\r\n");
      out.write("                <label for=\"tel\">TEL</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"int-area\">\r\n");
      out.write("                <input type=\"email\" name=\"email\" id=\"email\" autocomplete=\"off\" required>\r\n");
      out.write("                <label for=\"email\">email</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"btn-area\">\r\n");
      out.write("                <button id=\"btn\" type=\"submit\">SIGN UP</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"btn-area\">\r\n");
      out.write("                <button type=\"reset\">CANCEL</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </section>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        let id = $('#userid');\r\n");
      out.write("        let pw = $('#userpw');\r\n");
      out.write("        let pw2 = $('#userpw2');\r\n");
      out.write("        let name = $('#username');\r\n");
      out.write("        let tel = $('#tel');\r\n");
      out.write("        let email = $('email');\r\n");
      out.write("        let btn = $('#btn');\r\n");
      out.write("\r\n");
      out.write("        $(btn).on('click', function() {\r\n");
      out.write("            if($(id).val() == \"\") {\r\n");
      out.write("                $(id).next('label').addClass('warning');\r\n");
      out.write("                setTimeout(function() {\r\n");
      out.write("                    $('lable').removeClass('warning');\r\n");
      out.write("                },1500);\r\n");
      out.write("            }\r\n");
      out.write("            else if($(pw).val() ==\"\") {\r\n");
      out.write("                $(pw).next('label').addClass('warning');\r\n");
      out.write("            } else if($(pw2).val() ==\"\") {\r\n");
      out.write("                $(pw2).next('label').addClass('warning');\r\n");
      out.write("            } else if($(name).val() ==\"\") {\r\n");
      out.write("                $(name).next('label').addClass('warning');\r\n");
      out.write("            } else if($(tel).val() ==\"\") {\r\n");
      out.write("                $(tel).next('label').addClass('warning');\r\n");
      out.write("            } else if($(email).val() ==\"\") {\r\n");
      out.write("                $(email).next('label').addClass('warning');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("    <!--  비밀번호 확인 -->\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		function joinCheck(f) {\r\n");
      out.write("			if(f.userpw.value!=f.userpw2.value) {\r\n");
      out.write("				alert(\"비밀번호가 서로 일치 하지 않습니다.\");\r\n");
      out.write("				return false;\r\n");
      out.write("			} \r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<!-- 아이디 중복 체크 -->\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("	  	  function idCheck() {\r\n");
      out.write("	      var userid = $('#userid').val(); /*id값이 \"userid\"인 입력란의 value 값을 변수 id에 저장 */\r\n");
      out.write("	      $.ajax({\r\n");
      out.write("	          url:\"idCheck.do\", // Controller에서 인식할 주소\r\n");
      out.write("	          type:\"post\",    // POST 방식으로 전달\r\n");
      out.write("	          date:{userid: userid},\r\n");
      out.write("	          dataType: 'json',\r\n");
      out.write("	          success:function(cnt) { // Controller에서 넘어온 cnt값을 받는다.\r\n");
      out.write("	              if(cnt != 1) { // cnt가 1이 아니면 (=0일 경우) -> 사용 가능한 아이디\r\n");
      out.write("	                  $('.id_ok').css(\"display\", \"inline-block\");\r\n");
      out.write("	                  $('.id_already').css(\"display\", \"none\");\r\n");
      out.write("	              } else {    // cnt가 1일 경우 -> 이미 존재하는 아이디\r\n");
      out.write("	                  $('.id_already').css(\"display\", \"inline-block\");\r\n");
      out.write("	                  $('.id_ok').css(\"display\", \"none\");\r\n");
      out.write("	              }\r\n");
      out.write("	          },\r\n");
      out.write("	          /* error:function() {\r\n");
      out.write("	              alert(\"에러입니다.\");\r\n");
      out.write("	          } */\r\n");
      out.write("	      });\r\n");
      out.write("	  };\r\n");
      out.write("	</script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/member/joinForm.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path1");
      // /WEB-INF/views/member/joinForm.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/joinForm.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
