/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-09-20 05:00:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.include;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class gmovieInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/gyujin/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/gmovie/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/include/../include/header.jsp", Long.valueOf(1663063688388L));
    _jspx_dependants.put("jar:file:/D:/gyujin/project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/gmovie/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1659671595531L));
    _jspx_dependants.put("/WEB-INF/views/include/../include/footer.jsp", Long.valueOf(1663647295402L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>회사소개</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/normalize.css\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"//cdn.jsdelivr.net/npm/xeicon@2.3.3/xeicon.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"//code.jquery.com/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("    <style>\r\n");
      out.write("    body {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        height: 3000px;\r\n");
      out.write("    }\r\n");
      out.write("    section {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 2000px;\r\n");
      out.write("        background-image: linear-gradient(\r\n");
      out.write("            rgba(0, 0, 0, 0.8),\r\n");
      out.write("            rgba(0, 0, 0, 0.8)\r\n");
      out.write("        ), url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/bg-main-img.png);\r\n");
      out.write("        background-attachment: fixed;\r\n");
      out.write("        z-index: 0;\r\n");
      out.write("      }\r\n");
      out.write("      .gmovieInfo {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 15%;\r\n");
      out.write("        left: 30%;\r\n");
      out.write("        transform: (-50%, -50%);\r\n");
      out.write("        z-index: 999;\r\n");
      out.write("        color: #ffffff;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .gmovieInfo h2 {\r\n");
      out.write("        font-size: 35px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .gmovieInfo p {\r\n");
      out.write("        font-size: 20px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("      }\r\n");
      out.write("      .section {\r\n");
      out.write("        width: 1200px;\r\n");
      out.write("        height: 50px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        margin-top: 30px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        border-top: 2px solid black;\r\n");
      out.write("        border-bottom: 2px solid black;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .tab_list li {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        margin: 10px 30px 10px 0;\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      .tab_list li a {\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        font-size: large;\r\n");
      out.write("      }\r\n");
      out.write("      .company_wrap {\r\n");
      out.write("        width: 1200px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        padding: 50px 0 50px 0;\r\n");
      out.write("      }\r\n");
      out.write("      .company_wrap h2 {\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("      }\r\n");
      out.write("      .company_wrap h3 {\r\n");
      out.write("        color: #503396;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("      }\r\n");
      out.write("      .company_wrap p {\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("      }\r\n");
      out.write("      .valuable {\r\n");
      out.write("        width: 1200px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        margin-bottom: 100px;\r\n");
      out.write("      }\r\n");
      out.write("      .valuable img {\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("      }\r\n");
      out.write("      .value-tit {\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-size: 30px;\r\n");
      out.write("      }\r\n");
      out.write("      .bg_box {\r\n");
      out.write("        width: 1200px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        margin-top: 200px;\r\n");
      out.write("      }\r\n");
      out.write("      .bg_box h2 {\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("      }\r\n");
      out.write("      .bg_box h3 {\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #503396;\r\n");
      out.write("        font-size: 30px;\r\n");
      out.write("        margin-top: 20px;\r\n");
      out.write("        margin-bottom: 30px;\r\n");
      out.write("      }\r\n");
      out.write("      .point_box {\r\n");
      out.write("        width: 310px;\r\n");
      out.write("        height: 270px;\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        margin-right: 80px;\r\n");
      out.write("      }\r\n");
      out.write("      .point_box::after {\r\n");
      out.write("        content: '';\r\n");
      out.write("        display: block;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 50%;\r\n");
      out.write("        right: -60px;\r\n");
      out.write("        background-image: url(./imgs/ico-plus.png);\r\n");
      out.write("        width: 35px;\r\n");
      out.write("        height: 35px;\r\n");
      out.write("        margin-top: -20px; \r\n");
      out.write("      }\r\n");
      out.write("      .point_box:last-child::after {\r\n");
      out.write("        content: none;\r\n");
      out.write("      }\r\n");
      out.write("           \r\n");
      out.write("      .tit_box {\r\n");
      out.write("        color: #ffffff;\r\n");
      out.write("        background-color: #444444;\r\n");
      out.write("        width: 155px;\r\n");
      out.write("        height: 135px;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 50%;\r\n");
      out.write("        left: 50%;\r\n");
      out.write("        transform: translate(-50%, -50%);\r\n");
      out.write("      }\r\n");
      out.write("      .tit_box p {\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        padding-top: 25px;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        font-size: large;\r\n");
      out.write("      }\r\n");
      out.write("      .slogan {\r\n");
      out.write("        width: 1200px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("        margin-top: 80px;\r\n");
      out.write("      }\r\n");
      out.write("      .slogan h2 {\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("      }\r\n");
      out.write("      .slogan_box {\r\n");
      out.write("        border: 3px solid #ebebeb;\r\n");
      out.write("        width: 1100px;\r\n");
      out.write("        height: 160px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        margin: 25px 0 50px 0;\r\n");
      out.write("      }\r\n");
      out.write("      .slogan_box img {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 30%;\r\n");
      out.write("        left: 10%;\r\n");
      out.write("      }\r\n");
      out.write("      .slogan_box .sg_tit1 {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 27%;\r\n");
      out.write("        right: 35%;\r\n");
      out.write("        color: #037B94;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("      }\r\n");
      out.write("      .slogan_box .sg_tit2 {\r\n");
      out.write("        display: inline-block;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 40%;\r\n");
      out.write("        right: 10.5%;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("      }\r\n");
      out.write("      .identity {\r\n");
      out.write("        width: 1200px;\r\n");
      out.write("        margin: auto;\r\n");
      out.write("      }\r\n");
      out.write("      .identity h2 {\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        margin-bottom: 20px;\r\n");
      out.write("      }\r\n");
      out.write("      .identity p {\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        margin-bottom: 100px;\r\n");
      out.write("      }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<header id=\"header\">\r\n");
      out.write("    <div class=\"header_wrap\">\r\n");
      out.write("        <div class=\"header_top\">\r\n");
      out.write("            <a href=\"#\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/top_banner.jpg\" alt=\"top_banner\">\r\n");
      out.write("                <button type=\"button\" class=\"btn-close btn-close-white\" aria-label=\"Close\"></button>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div> \r\n");
      out.write("        <div class=\"header_container\">\r\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\">\r\n");
      out.write("                <div class=\"textbox_wrap\">\r\n");
      out.write("                    <div class=\"textbox\">G</div>\r\n");
      out.write("                    <div class=\"textbox\">M</div>\r\n");
      out.write("                    <div class=\"textbox\">O</div>\r\n");
      out.write("                    <div class=\"textbox\">V</div>\r\n");
      out.write("                    <div class=\"textbox\">I</div>\r\n");
      out.write("                    <div class=\"textbox\">E</div>\r\n");
      out.write("                    <div class=\"textbox2\">절찬상영중</div>                 \r\n");
      out.write("                </div> \r\n");
      out.write("            </a>          \r\n");
      out.write("            <div  class=\"left_link\">\r\n");
      out.write("                <a href=\"#\"><i class=\"xi-facebook-official xi-x\"></i>페이스북</a>\r\n");
      out.write("                <a href=\"#\"><i class=\"xi-youtube-play xi-x\"></i>유튜브</a>\r\n");
      out.write("                <a href=\"#\"><i class=\"xi-instagram xi-x\"></i>인스타그램</a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"right_link\">\r\n");
      out.write("            <!-- 로그인 전 -->\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            <!-- 로그인 후 --> \r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            <!-- 관리자 로그인 일 때 -->\r\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            </div>           \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"topMenu\">\r\n");
      out.write("        <ul class=\"menu01\">\r\n");
      out.write("            <li><span>예매</span>\r\n");
      out.write("                <ul class=\"dept01\">\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">예매하기</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">상영시간표</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">할인안내</a></li>\r\n");
      out.write("                    \r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class=\"menu01\">\r\n");
      out.write("            <li><span>영화</span>\r\n");
      out.write("                <ul class=\"dept01\">\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">홈</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">현재상영작</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">상영예정작</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class=\"menu01\">\r\n");
      out.write("            <li><span>영화관</span>\r\n");
      out.write("                <ul class=\"dept01\">\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">스페셜관</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">서울</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">경기/인천</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class=\"menu01\">\r\n");
      out.write("            <li><span>이벤트</span>\r\n");
      out.write("                <ul class=\"dept01\">\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">홈</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">시사회/무대인사</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">제휴할인</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class=\"menu01\">\r\n");
      out.write("            <li><span>스토어</span>\r\n");
      out.write("                <ul class=\"dept01\">\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">베스트</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">관람권</a></li>\r\n");
      out.write("                    <li id=\"nop\"><a href=\"#\">스낵음료</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"none\">\r\n");
      out.write("    </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <script>\r\n");
      out.write("        jQuery(document).ready(function($) {\r\n");
      out.write("            $(\"#navigation-list\").hide();\r\n");
      out.write("            $(\".menuBtn\").click(function() {\r\n");
      out.write("                $(\"#navigation-list\").slideToggle(300);\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        $(document).on('mouseover', '.topMenu span', function() {\r\n");
      out.write("        $('.dept01').slideDown(500);\r\n");
      out.write("        });\r\n");
      out.write("        $(document).on('mouseover', 'div', function () {\r\n");
      out.write("        if (!$(this).hasClass('topMenu')) {\r\n");
      out.write("            $('.dept01').slideUp(500);\r\n");
      out.write("        }\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("        <section>\r\n");
      out.write("            <div class=\"gmovieInfo\">\r\n");
      out.write("                <h2>GMOVIE 소개</h2>\r\n");
      out.write("                <br>\r\n");
      out.write("                <p>새로운 이야기를 만나고, 함께 어울려 놀고,즐거운 경험을 공유하는 공간</p>    \r\n");
      out.write("            </div>           \r\n");
      out.write("        </section> \r\n");
      out.write("        <div class=\"section\">\r\n");
      out.write("            <ul class=\"tab_list\">\r\n");
      out.write("                <li><a href=\"#\">회사개요</a></li>\r\n");
      out.write("                <li><a href=\"#\">오시는길</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"company_wrap\">\r\n");
      out.write("            <h2>미션(Mission)</h3>\r\n");
      out.write("            <h3>사람들과 공유할 수 있는, 공간경험을 만듭니다.</h3>\r\n");
      out.write("            <p>\r\n");
      out.write("                우리는 사람들에게 '즐겁고 행복한 일상'을 전달하기 위해 존재합니다. <br>\r\n");
      out.write("                가치있는 콘텐트 제공으로 일상에 열감을 주는 '인생극장'을 넘어 공간 사업의 다양화를 중심으로 ‘즐거운 인생경험’을 제공하는 공간을 만듭니다.\r\n");
      out.write("                <br><br>\r\n");
      out.write("                GMOVIE를 경험한 오늘을 행복한 마음으로 공유할 수 있도록\r\n");
      out.write("                MEET PLAY SHARE, GMOVIE\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"valuable\">\r\n");
      out.write("            <div class=\"value-tit\">\r\n");
      out.write("                <p>VALUABLE INFLUENCE<br>가치있는 영향력</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/img-valuable2.png\" alt=\"valuable\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"bg_box\">\r\n");
      out.write("            <h2>핵심가치 (Core Value)</h2>\r\n");
      out.write("            <h3>GMOVIE가 추구하는 핵심가치는 '공감 + 창조 + 재미' 입니다.</h3>\r\n");
      out.write("            <div class=\"point_box\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/bg-point01_2.png);\">\r\n");
      out.write("                <div class=\"tit_box\">\r\n");
      out.write("                    <p>공감<br>사람에 대한<br>이해와 배려</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"point_box\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/bg-point02_2.png);\">\r\n");
      out.write("                <div class=\"tit_box\">\r\n");
      out.write("                    <p>창조<br>일상을 새롭게 하는<br>도전과 열정</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"point_box\" style=\"background-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/bg-point03_2.png);\">\r\n");
      out.write("                <div class=\"tit_box\">\r\n");
      out.write("                    <p>재미<br>스스로<br>즐거워하기</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"slogan\">\r\n");
      out.write("            <h2>브랜드 슬로건 (Brand Slogan)</h2>\r\n");
      out.write("            <div class=\"slogan_box\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/img-lifetheater-tm2.png\" alt=\"슬로건\">\r\n");
      out.write("                <p class=\"sg_tit1\">MEET PLAY SHARE, GMOVIE</p><p class=\"sg_tit2\">새로운 이야기를 만나고,함께 어울려 놀고, 즐거운 경험을 공유하는 공간</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"identity\">\r\n");
      out.write("            <h2>BI (Brand identity)</h2>\r\n");
      out.write("            <p>\r\n");
      out.write("                2017년 새롭게 선보인 지무비의 브랜드아이덴티티는 6개의 황금비율의 박스와 영문 지무비라이프체로 조합되어 기존 지무비의 아이덴티티의 핵심 정신을 계\r\n");
      out.write("                <br>승함과 동시에 사용상의 효율성과 확장성을 확보했습니다. <br>\r\n");
      out.write("                시각적 안정감을 주는 5:8 황금비율의 박스들은 지무비의 공간을 상징하며, 보라 계열의 인디고 컬러는 창의적 콘텐트로 공간을 채워가겠다는 의미입니다.<br>\r\n");
      out.write("                나아가 극장업의 본질에 충실하되 공간을 중심으로 다양한 고객 경험을 위해 창의적 시도를 멈추지 않겠다는 철학을 담았습니다.    \r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("       ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<footer id=\"footer\">\r\n");
      out.write("<div class=\"footer_wrap\">\r\n");
      out.write("    <div class=\"footer_top\">\r\n");
      out.write("        <ul class=\"fnb\">\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/gmovieInfo.do\">회사소개</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/recruit.do\">인재채용</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/social.do\">사회공헌</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/partner.do\">제휴/광고/부대사업문의</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/rules.do\">법적고지</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/emreject.do\">이메일주소무단수집거부</a></li>\r\n");
      out.write("            <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/management.do\">윤리경영</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"footer_bottom\">\r\n");
      out.write("        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/imgs/footer_logo.png\" alt=\"푸터로고\" class=\"footerLogo\">\r\n");
      out.write("        <span>\r\n");
      out.write("            <strong>주소 : 경기도 시흥시 은계번영길 9, 4F 409~411(은행동 골드웨이)</strong>                   \r\n");
      out.write("        </span>\r\n");
      out.write("        <span>\r\n");
      out.write("            <strong>E-mail : </strong>\r\n");
      out.write("                gmovie@naver.com\r\n");
      out.write("        </span>\r\n");
      out.write("        <br>\r\n");
      out.write("        <span>\r\n");
      out.write("            <strong>상호명 : </strong>\r\n");
      out.write("                GMOVIE\r\n");
      out.write("        </span>\r\n");
      out.write("        <span>\r\n");
      out.write("            <strong>대표이사 : </strong>\r\n");
      out.write("                이규진\r\n");
      out.write("        </span>\r\n");
      out.write("        <span>\r\n");
      out.write("            <strong>사업자등록번호 : </strong>\r\n");
      out.write("            647-16-02021\r\n");
      out.write("        </span>\r\n");
      out.write("        <span>\r\n");
      out.write("            <strong>통신판매업신고번호 : </strong>\r\n");
      out.write("                2022-경기시흥-1113\r\n");
      out.write("        </span>\r\n");
      out.write("        <p>COPYRIGHT ⓒ2022 GMOVIE All right Reserved</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</footer>");
      out.write("      \r\n");
      out.write("        \r\n");
      out.write("    <footer id=\"footer\"></footer>\r\n");
      out.write("    \r\n");
      out.write("        <script type=\"text/javascript\">\r\n");
      out.write("            $(window).scroll(function() {\r\n");
      out.write("                var scroll_position = $(window).scrollTop()/2;\r\n");
      out.write("                $('section').css({\r\n");
      out.write("                    'background-position-x' : - scroll_position + 'px',\r\n");
      out.write("                })\r\n");
      out.write("            })\r\n");
      out.write("        </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/include/gmovieInfo.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path1");
      // /WEB-INF/views/include/gmovieInfo.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/include/gmovieInfo.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/include/../include/header.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("path1");
      // /WEB-INF/views/include/../include/header.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/include/../include/header.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/include/../include/header.jsp(33,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sid }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/loginForm.do\">\r\n");
          out.write("                    <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/imgs/loginPassword.png\" alt=\"\">\r\n");
          out.write("                    		로그인\r\n");
          out.write("                </a>\r\n");
          out.write("                <a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/agreement.do\">\r\n");
          out.write("                    <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/imgs/loginJoin.png\" alt=\"\">\r\n");
          out.write("                   		 	회원가입\r\n");
          out.write("                </a>\r\n");
          out.write("                <a href=\"#\">\r\n");
          out.write("                    <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/imgs/loginCustomer.png\" alt=\"\">\r\n");
          out.write("                   			 고객센터\r\n");
          out.write("                </a>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/include/../include/header.jsp(48,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sid }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("				<span style=\"font-weight: bold; font-size: 1.3em\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님</span>\r\n");
          out.write("            	<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/read.do\">마이페이지</a>\r\n");
          out.write("            	<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/logout.do\">로그아웃</a>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/include/../include/header.jsp(54,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sid == 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("       \r\n");
          out.write("                <button type=\"button\" class=\"menuBtn\">\r\n");
          out.write("                    <i class=\"xi-bars xi-x\"></i>\r\n");
          out.write("                    <nav id=\"navigation-list\" class=\"navList\">\r\n");
          out.write("                        <ul>\r\n");
          out.write("                            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/list.do\">회원 목록</a></li>\r\n");
          out.write("                            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/board/list.do\">게시판 목록</a></li>\r\n");
          out.write("                            <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/board/writeForm.do\">게시판 등록</a></li>\r\n");
          out.write("                        </ul>\r\n");
          out.write("                    </nav>\r\n");
          out.write("                </button>\r\n");
          out.write("             ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /WEB-INF/views/include/../include/footer.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("path1");
      // /WEB-INF/views/include/../include/footer.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/include/../include/footer.jsp(5,0) '${pageContext.request.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }
}
